force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <description>Prédio a ter seus apartamentos e vagas vendidos pela construtorarédio a ter seus apartamentos e vagas vendidos pela construtora</description>
    <label>Empreendimento</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nome de Empreendimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/PrecoTipoUnidade__c.object-meta.xml
<CustomObject>
    <label>Preço do Tipo de Unidade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Nome do Preço do Tipo de Unidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preços de Tipos de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/fields/AreaTotal__c.field-meta.xml
<CustomField>
    <fullName>AreaTotal__c</fullName>
    <label>Área Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tipo de Unidades</relationshipLabel>
    <relationshipName>TipoUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/fields/TipoRegistroUnidades__c.field-meta.xml
<CustomField>
    <fullName>TipoRegistroUnidades__c</fullName>
    <label>Tipo de registro das Unidades</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartamento</fullName>
            </value>
            <value>
                <fullName>Vaga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/fields/VagasDeficientes__c.field-meta.xml
<CustomField>
    <fullName>VagasDeficientes__c</fullName>
    <label>Vagas para deficiêntes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/selector/TipoUnidadeSelector.cls
public class TipoUnidadeSelector {
    public static List<TipoUnidade__c> getUnitTypeData() {
        return [SELECT Id, Name
                FROM TipoUnidade__c];
    }

    public static List<TipoUnidade__c> getUnitTypeByName(List<String> unitTypeNames) {
        return [SELECT Id, Name, AreaTotal__c, Banheiros__c, Dormitorios__c, Suites__c, 
                VagasCarros__c, VagasMotos__c, VagasDeficientes__c, Empreendimento__c, 
                UnidadesPorAndar__c, TipoRegistroUnidades__c 
                FROM TipoUnidade__c
                WHERE Name in :unitTypeNames];
    }

    public static List<TipoUnidade__c> getUnitTypeWithoutPrice(List<Id> enterprises) {
        List<PrecoTipoUnidade__c> unitWithPrices = [SELECT TipoUnidade__c, Id FROM PrecoTipoUnidade__c WHERE TipoUnidade__r.Empreendimento__c IN :enterprises];
        List<TipoUnidade__c> unitTypes = [SELECT Id, Name FROM TipoUnidade__c WHERE Empreendimento__c in :enterprises];

        Map<Id, String> newMap = new Map<Id, String>();

        for(PrecoTipoUnidade__c p : unitWithPrices) {
            newMap.put(p.TipoUnidade__c, p.Id);
        }

        List<TipoUnidade__c> checkedUnitTypes = new List<TipoUnidade__c>();
        for(TipoUnidade__c u : unitTypes) {
            if(!newMap.containsKey(u.Id)){
                checkedUnitTypes.add(u);
            }
        }
        return checkedUnitTypes;
    }
}