force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <description>Prédio a ter seus apartamentos e vagas vendidos pela construtorarédio a ter seus apartamentos e vagas vendidos pela construtora</description>
    <label>Empreendimento</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nome de Empreendimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/fields/AreaTotal__c.field-meta.xml
<CustomField>
    <fullName>AreaTotal__c</fullName>
    <label>Área Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tipo de Unidades</relationshipLabel>
    <relationshipName>TipoUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/fields/VagasDeficientes__c.field-meta.xml
<CustomField>
    <fullName>VagasDeficientes__c</fullName>
    <label>Vagas para deficiêntes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Torre__c/Torre__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades por andar ou prédio</description>
    <label>Torre</label>
    <nameField>
        <displayFormat>T{0000}</displayFormat>
        <label>Código de Torre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Torre__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Torres</relationshipLabel>
    <relationshipName>Torres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unidade__c/Unidade__c.object-meta.xml
<CustomObject>
    <description>Um apartamento ou vaga de garagem de um prédio vendido ou disponível para compra por uma construtora</description>
    <label>Unidade</label>
    <nameField>
        <label>Código da Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unidade__c/fields/AndarExibicao__c.field-meta.xml
<CustomField>
    <fullName>AndarExibicao__c</fullName>
    <label>Andar de exibição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/AreaComum__c.field-meta.xml
<CustomField>
    <fullName>AreaComum__c</fullName>
    <label>Área coumm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/AreaTotal__c.field-meta.xml
<CustomField>
    <fullName>AreaTotal__c</fullName>
    <label>Área total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Banheiros__c.field-meta.xml
<CustomField>
    <fullName>Banheiros__c</fullName>
    <label>Banheiros</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Dormitorios__c.field-meta.xml
<CustomField>
    <fullName>Dormitorios__c</fullName>
    <label>Dormitórios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/FinalUnidade__c.field-meta.xml
<CustomField>
    <fullName>FinalUnidade__c</fullName>
    <label>Final da Unidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/FracaoIdeal__c.field-meta.xml
<CustomField>
    <fullName>FracaoIdeal__c</fullName>
    <label>Fração Ideal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível</fullName>
            </value>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Suites__c.field-meta.xml
<CustomField>
    <fullName>Suites__c</fullName>
    <label>Suítes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/Torre__c.field-meta.xml
<CustomField>
    <fullName>Torre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Torre</label>
    <referenceTo>Torre__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/VagasCarros__c.field-meta.xml
<CustomField>
    <fullName>VagasCarros__c</fullName>
    <label>Vagas para carros</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/VagasDeficientes__c.field-meta.xml
<CustomField>
    <fullName>VagasDeficientes__c</fullName>
    <label>Vagas para deficientes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidade__c/fields/VagasMotos__c.field-meta.xml
<CustomField>
    <fullName>VagasMotos__c</fullName>
    <label>Vagas para motos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DTO/UnidadeDTO.cls
public class UnidadeDTO {
        @AuraEnabled
        public string Name{get;set;}
        @AuraEnabled
        public string Status{get;set;}
        @AuraEnabled
        public id TipoUnidade{get;set;}
        @AuraEnabled
        public string TipoUnidadeName{get;set;}
        @AuraEnabled
        public Integer AndarExibicao{get;set;}
        @AuraEnabled
        public string FinalUnidade{get;set;}
        @AuraEnabled
        public Integer AreaComum{get;set;}
        @AuraEnabled
        public Integer AreaTotal{get;set;}
        @AuraEnabled
        public Decimal FracaoIdeal{get;set;}
        @AuraEnabled
        public Integer Dormitorios{get;set;}
        @AuraEnabled
        public Integer Suites{get;set;}
        @AuraEnabled
        public Integer VagasCarros{get;set;}
        @AuraEnabled
        public id Torre{get;set;}
        @AuraEnabled
        public id Empreendimento{get;set;}
        @AuraEnabled
        public string TipoRegistroUnidade{get;set;}
        @AuraEnabled
        public Integer VagasDeficientes{get;set;}
        @AuraEnabled
        public Integer VagasMotos{get;set;}
        @AuraEnabled
        public Integer Banheiros{get;set;}

        public Unidade__c getUnit() {
            return new Unidade__c(
                    Name = this.Name,
                    Status__c = this.Status,
                    TipoUnidade__c = this.TipoUnidade,
                    AndarExibicao__c = this.AndarExibicao,
                    FinalUnidade__c = this.FinalUnidade,
                    AreaComum__c = this.AreaComum,
                    AreaTotal__c = this.AreaTotal,
                    FracaoIdeal__c = this.FracaoIdeal,
                    Dormitorios__c = this.Dormitorios,
                    Suites__c = this.Suites,
                    VagasCarros__c = this.VagasCarros,
                    Torre__c = this.Torre,
                    Empreendimento__c = this.Empreendimento,
                    VagasDeficientes__c = this.VagasDeficientes,
                    VagasMotos__c = this.VagasMotos,
                    Banheiros__c = this.Banheiros
                );
        }
}