force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <description>Prédio a ter seus apartamentos e vagas vendidos pela construtorarédio a ter seus apartamentos e vagas vendidos pela construtora</description>
    <label>Empreendimento</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nome de Empreendimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Vendas</label>
    <nameField>
        <label>Nome da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabelas de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo responsável por indicar se esta tabela está ativa atualmente ou não</description>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/DataInicioVigencia__c.field-meta.xml
<CustomField>
    <fullName>DataInicioVigencia__c</fullName>
    <label>Data de início de vigência</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabelas de Vendas</relationshipLabel>
    <relationshipName>TabelasVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selector/TabelaVendasSelector.cls
public class TabelaVendasSelector {
    public static List<TabelaVendas__c> getSalesTablesByEnterprise(List<Id> enterprises, Boolean isActive, Boolean isFuture) {
        if(isFuture) {
            if(isActive) {
                return [SELECT Id, Name 
                        FROM TabelaVendas__c 
                        WHERE Empreendimento__c IN :enterprises];
            } else {
                return [SELECT Id, Name 
                        FROM TabelaVendas__c 
                        WHERE Empreendimento__c IN :enterprises AND Ativa__c = false];
            }
        } else {
            if(isActive) {
                return [SELECT Id, Name 
                        FROM TabelaVendas__c 
                        WHERE Empreendimento__c IN :enterprises AND DataInicioVigencia__c < TODAY];
            } else {
                return [SELECT Id, Name 
                        FROM TabelaVendas__c 
                        WHERE Empreendimento__c IN :enterprises AND DataInicioVigencia__c < TODAY AND Ativa__c = false];
            }
        }
    }

    public static List<TabelaVendas__c> getSalesTableEnterprise(List<Id> salesTable) {
        return [SELECT Empreendimento__c
                FROM TabelaVendas__c
                WHERE ID IN :salesTable];
    }
}