force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <description>Prédio a ter seus apartamentos e vagas vendidos pela construtorarédio a ter seus apartamentos e vagas vendidos pela construtora</description>
    <label>Empreendimento</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nome de Empreendimento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/PrecoTipoUnidade__c.object-meta.xml
<CustomObject>
    <label>Preço do Tipo de Unidade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Nome do Preço do Tipo de Unidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preços de Tipos de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/PrecoAtual__c.field-meta.xml
<CustomField>
    <fullName>PrecoAtual__c</fullName>
    <label>Preço atual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TabelaVendas__c.field-meta.xml
<CustomField>
    <fullName>TabelaVendas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Vendas</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Vendas</label>
    <nameField>
        <label>Nome da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabelas de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabelas de Vendas</relationshipLabel>
    <relationshipName>TabelasVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tipo de Unidades</relationshipLabel>
    <relationshipName>TipoUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selector/PrecoTipoUnidadeSelector.cls
public class PrecoTipoUnidadeSelector {
    public static List<PrecoTipoUnidade__c> getPriceTypes() {
        return [SELECT Id, TipoUnidade__c, TabelaVendas__c 
                FROM PrecoTipoUnidade__c];
    }

    public static List<PrecoTipoUnidade__c> getPriceTypesBySalesTable(List<Id> salesTables) {
        return [SELECT Id, TabelaVendas__r.Empreendimento__r.Name, TipoUnidade__r.Name, TabelaVendas__r.Name, PrecoAtual__c, TipoUnidade__c, TabelaVendas__c
                FROM PrecoTipoUnidade__c
                WHERE TabelaVendas__c in :salesTables];
    }

    public static Boolean verifyUnitType(List<Id> unitTypes) {
        List<PrecoTipoUnidade__c> result = [SELECT TipoUnidade__c FROM PrecoTipoUnidade__c WHERE TipoUnidade__c IN :unitTypes];
        if(result.size() > 0) {
            return false;
        } else {
            return true;
        }
    }
}