force-app/main/default/objects/PrecoTipoUnidade__c/PrecoTipoUnidade__c.object-meta.xml
<CustomObject>
    <label>Preço do Tipo de Unidade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Nome do Preço do Tipo de Unidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preços de Tipos de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/PrecoAnterior__c.field-meta.xml
<CustomField>
    <fullName>PrecoAnterior__c</fullName>
    <label>Preço anterior</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/PrecoAtual__c.field-meta.xml
<CustomField>
    <fullName>PrecoAtual__c</fullName>
    <label>Preço atual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TabelaVendas__c.field-meta.xml
<CustomField>
    <fullName>TabelaVendas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Vendas</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/ValorAtualizacaoPercentual__c.field-meta.xml
<CustomField>
    <fullName>ValorAtualizacaoPercentual__c</fullName>
    <label>Valor da atualização percentual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/ValorAtualizaNominal__c.field-meta.xml
<CustomField>
    <fullName>ValorAtualizaNominal__c</fullName>
    <label>Valor da atualização nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Vendas</label>
    <nameField>
        <label>Nome da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabelas de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DTO/PrecoTipoUnidadeDTO.cls
public class PrecoTipoUnidadeDTO {
    @AuraEnabled
    public String Empreendimento{get;set;}
    @AuraEnabled
    public String TabelaVendas{get;set;}
    @AuraEnabled
    public String TipoUnidade{get;set;}
    @AuraEnabled
    public Decimal IndiceAtualizacao{get;set;}
    @AuraEnabled
    public Decimal ValorAtualizacao{get;set;}
    @AuraEnabled
    public Decimal ValorAdicional{get;set;}
    @AuraEnabled
    public Decimal ValorAposAtualizacao{get;set;}
    @AuraEnabled
    public Decimal ValorAtual{get;set;}
    @AuraEnabled
    public Id Id{get;set;}
    @AuraEnabled
    public Id TabelaVendasId{get;set;}
    @AuraEnabled
    public Id TipoUnidadeId{get;set;}

    public PrecoTipoUnidade__c getPriceType() { 
        return new PrecoTipoUnidade__c(
            Id = this.Id,
            PrecoAnterior__c = this.ValorAtual,
            PrecoAtual__c = this.ValorAposAtualizacao,
            ValorAtualizacaoPercentual__c = this.IndiceAtualizacao*100,
            ValorAtualizaNominal__c = this.ValorAdicional
        );
    }

    public PrecoTipoUnidade__c getPriceTypeWithLookup() { 
        return new PrecoTipoUnidade__c(
            Id = this.Id,
            PrecoAnterior__c = this.ValorAtual,
            PrecoAtual__c = this.ValorAposAtualizacao,
            ValorAtualizacaoPercentual__c = this.IndiceAtualizacao,
            ValorAtualizaNominal__c = this.ValorAdicional,
            TipoUnidade__c = this.TipoUnidadeId,
            TabelaVendas__c = this.TabelaVendasId
        );
    }
}