force-app/main/default/objects/PrecoTipoUnidade__c/PrecoTipoUnidade__c.object-meta.xml
<CustomObject>
    <label>Preço do Tipo de Unidade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Nome do Preço do Tipo de Unidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preços de Tipos de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TabelaVendas__c.field-meta.xml
<CustomField>
    <fullName>TabelaVendas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Vendas</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Vendas</label>
    <nameField>
        <label>Nome da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabelas de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/domain/PrecoTipoUnidadeDomain.cls
public class PrecoTipoUnidadeDomain {
    List<PrecoTipoUnidade__c> newPriceType;
    public PrecoTipoUnidadeDomain(List<PrecoTipoUnidade__c> p) {
        this.newPriceType = p;
    }

    public PrecoTipoUnidadeDomain() {
        this.newPriceType = new List<PrecoTipoUnidade__c>();
    }

    public void checkPriceTypeLookups() {
        Map<Id, Map<Id, PrecoTipoUnidade__c>> itemTypeAndPriceTableMap = new Map<Id, Map<Id, PrecoTipoUnidade__c>>();
        List<PrecoTipoUnidade__c> selectedTypes = PrecoTipoUnidadeSelector.getPriceTypes();

        for(PrecoTipoUnidade__c p : selectedTypes) {
            if(itemTypeAndPriceTableMap.containsKey(p.TipoUnidade__c)) {
                itemTypeAndPriceTableMap.get(p.TipoUnidade__c).put(p.TabelaVendas__c, p);
            } else {
                itemTypeAndPriceTableMap.put(p.TipoUnidade__c, new Map<Id, PrecoTipoUnidade__c>{p.TabelaVendas__c => p});
            }
        }
        for(PrecoTipoUnidade__c p : this.newPriceType) {
            if(itemTypeAndPriceTableMap.containsKey(p.TipoUnidade__c) && itemTypeAndPriceTableMap.get(p.TipoUnidade__c).containsKey(p.TabelaVendas__c)) {
                p.addError(System.Label.MensagemTipoPrecoDuplicado);
            }
        }
    }

    public void transferDataForUpdate(String pricesToTransfer) {
        try{
            List<PrecoTipoUnidadeDTO> typesList = (List<PrecoTipoUnidadeDTO>)JSON.deserialize(pricesToTransfer, List<PrecoTipoUnidadeDTO>.class);
            for(PrecoTipoUnidadeDTO dto : typesList) {
                this.newPriceType.add(dto.getPriceType());
            }
        } catch(Exception e) {
            system.debug(e);
        }
    }

    public void transferDataForInsert(String pricesToTransfer) {
        try{
            List<PrecoTipoUnidadeDTO> typesList = (List<PrecoTipoUnidadeDTO>)JSON.deserialize(pricesToTransfer, List<PrecoTipoUnidadeDTO>.class);
            for(PrecoTipoUnidadeDTO dto : typesList) {
                this.newPriceType.add(dto.getPriceTypeWithLookup());
            }
        } catch(Exception e) {
            system.debug(e);
        }
    }

    public Boolean insertPriceType() {
        system.debug('Fez algo');
        system.debug(this.newPriceType);
        if(!this.newPriceType.isEmpty()) {
            insert this.newPriceType;
            return true;
        }
        return false;
    }

    public Boolean updatePriceType() {
        system.debug('Fez algo');
        system.debug(this.newPriceType);
        if(!this.newPriceType.isEmpty()) {
            update this.newPriceType;
            return true;
        }
        return false;
    }
}