force-app/main/default/objects/PrecoTipoUnidade__c/PrecoTipoUnidade__c.object-meta.xml
<CustomObject>
    <label>Preço do Tipo de Unidade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Nome do Preço do Tipo de Unidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preços de Tipos de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/PrecoAtual__c.field-meta.xml
<CustomField>
    <fullName>PrecoAtual__c</fullName>
    <label>Preço atual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TabelaVendas__c.field-meta.xml
<CustomField>
    <fullName>TabelaVendas__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Vendas</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrecoTipoUnidade__c/fields/TipoUnidade__c.field-meta.xml
<CustomField>
    <fullName>TipoUnidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Unidade</label>
    <referenceTo>TipoUnidade__c</referenceTo>
    <relationshipLabel>Preços de Tipos de Unidades</relationshipLabel>
    <relationshipName>PrecosTiposUnidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Vendas</label>
    <nameField>
        <label>Nome da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabelas de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/DataInicioVigencia__c.field-meta.xml
<CustomField>
    <fullName>DataInicioVigencia__c</fullName>
    <label>Data de início de vigência</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/DescontoMoeda__c.field-meta.xml
<CustomField>
    <fullName>DescontoMoeda__c</fullName>
    <label>Desconto (R$)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/DescontoPercentual__c.field-meta.xml
<CustomField>
    <fullName>DescontoPercentual__c</fullName>
    <label>Desconto (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TipoUnidade__c/TipoUnidade__c.object-meta.xml
<CustomObject>
    <description>Registro para agrupamento de Unidades com características homogêneas, como preço e dimensões</description>
    <label>Tipo de Unidade</label>
    <nameField>
        <label>Nome do Tipo de Unidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de Unidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoUnidade__c/fields/VagasDeficientes__c.field-meta.xml
<CustomField>
    <fullName>VagasDeficientes__c</fullName>
    <label>Vagas para deficiêntes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/test/PrecoTipoUnidadeTest.cls
@isTest
public class PrecoTipoUnidadeTest {  
    @TestSetup
    static void makeData(){
        List<TipoUnidade__c> listUnitTypes = new List<TipoUnidade__c> {
            new TipoUnidade__c(Dormitorios__c = 2, Suites__c = 1),
            new TipoUnidade__c(Dormitorios__c = 4, VagasDeficientes__c = 1)
        };
        insert listUnitTypes;

        List<TabelaVendas__c> listSalesTables =  new List<TabelaVendas__c> {
            new TabelaVendas__c(DataInicioVigencia__c = Date.today(), DescontoPercentual__c = 5),
            new TabelaVendas__c(DataInicioVigencia__c = Date.today(), DescontoMoeda__c = 10)
        };
        insert listSalesTables;

        PrecoTipoUnidade__c pu = new PrecoTipoUnidade__c(
            TipoUnidade__c = listUnitTypes[0].id,
            TabelaVendas__c = listSalesTables[0].id
        );
        insert pu;
    }
    
    @isTest
    public static void testDuplicatePriceType() {
        List<TipoUnidade__c> listUnitTypes = [SELECT Id FROM TipoUnidade__c];
        List<TabelaVendas__c> listSalesTables = [SELECT Id FROM TabelaVendas__c];

        PrecoTipoUnidade__c p1 = new PrecoTipoUnidade__c(
            PrecoAtual__c = 20,
            TipoUnidade__c = listUnitTypes[1].id,
            TabelaVendas__c = listSalesTables[0].id
        );

        PrecoTipoUnidade__c p2 = new PrecoTipoUnidade__c(
            PrecoAtual__c = 20,
            TipoUnidade__c = listUnitTypes[0].id,
            TabelaVendas__c = listSalesTables[1].id
        );

        PrecoTipoUnidade__c p3 = new PrecoTipoUnidade__c(
            PrecoAtual__c = 20,
            TipoUnidade__c = listUnitTypes[1].id,
            TabelaVendas__c = listSalesTables[0].id
        );


        insert p1;
        insert p2;

        try{
            insert p3;
        } catch(Exception e){
            system.debug('Error ' + e);
        }        

        List<PrecoTipoUnidade__c> testList = [SELECT Id FROM PrecoTipoUnidade__c];
        system.assertEquals(3, testList.size());
    }
}